# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:
  
jobs:
  diags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          environment: azurecloud
          allow-no-subscriptions: false
          

      - name: Validate Infrastructure deployment
        uses: Azure/cli@1.0.4
        with:
          #azcliversion: ${{ env.AZCLIVERSION }}
          inlineScript: |
            az group list -o table
